# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "Cerallin的笔记本"
subtitle: "瞎折腾～～"
description: Cerallin的笔记本，记录日常工作和日常折腾（笑），转载请注明出处。

signature: Roses are red. I'm going to bed.
keywords:
  - Coding
  - 编程
  - 操作系统
  - 程序员
author: Cerallin
language: zh
timezone: "Asia/Shanghai"
auto_spacing: true
toc: true

since_year: 2021

post_copy:
  text: 署名
  text_en: CC BY 4.0
  link: https://creativecommons.org/licenses/by/4.0/deed.zh

menu:
  归档:
    widget: Archives
  计算机与通信工程:
    name: 计算机与通信工程
    widget: Posts
    show_num: 4
  材料科学与工程:
    name: 材料科学与工程
    widget: Posts
    show_num: 4
  瞎折腾:
    name: 瞎折腾
    widget: Posts
    show_num: 6
  浅思:
    name: 浅思
    widget: Posts
    show_num: 4
  标签:
    widget: Tags

header_menu:
  关于: /about

footer_links:
  - - text: Google Scholar
      url: https://scholar.google.com/
    - text: Google patents
      url: https://patents.google.com/
    - text: Bing Academic
      url: https://bing.com/academic/
  - - text: Web of Science
      url: https://www.webofscience.com/
    - text: Science Direct
      url: https://www.sciencedirect.com/
    - text: 中国知网
      url: https://www.cnki.net/
  - - text: arXiv
      url: https://arxiv.org/
    - text: JSTOR
      url: https://www.jstor.org/
    - text: PubMed Central
      url: https://www.ncbi.nlm.nih.gov/pmc/
  - - text: MSI Eureka
      url: https://search.msi-eureka.com/search
    - text: GitHub
      url: https://github.com/cerallin/
    - text: KUKE音乐
      url: https://www.kuke.com/

# Archive page
archive_type: "yearly"
tag_type: "monthly"
show_count: false

# 备案
beian:
  enable: false

# hexo-renderer-pandoc 0.5.0
pandoc:
  pandocPath: /opt/dependencies/pandoc
  timeout: 1000
  args:
    - --filter
    - pandoc-crossref
    - --csl
    # - GB7714.csl
    # - elsevier-with-titles.csl
    - ieee.csl
    - --citeproc
    - -M
    - link-citations=true
    - -M
    - crossrefYaml=_crossref.yml
    - --mathjax

fix_cjk_spacing: true

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://cerallin.github.io/notes
root: /notes/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:month_:day_:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 4
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

tag_options:
  orderby: length
  order: -1
  amount: 20

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: []
exclude: []
ignore: []

# Extensions
## Plugins: https://hexo.io/plugins/
plugins:
  - hexo-generator-feed
## Themes: https://hexo.io/themes/
theme: hexo-theme-yuzu

archive_generator:
  enabled: true
  per_page: 16
  yearly: true
  monthly: true
  daily: false
  order_by: -date

category_generator:
  per_page: 8
  order_by: -date

tag_generator:
  per_page: 8
  order_by: -date

html_minifier:
  collapseBooleanAttributes: true
  collapseWhitespace: true
  removeComments: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  minifyJS: true
  minifyCSS: false

clean_css:
  level: 2
  exclude:
    - "*.min.css"

text_autospace_filter:
  enable: true
  inject_css: true
  tag_name: "hl"
  entry: "body"

viz_renderer:
  enable: true

# cdn
cdn:
  enable: false
  base: http://notes-test.cerallin.top
  tail: t=1639496120

visit_count:
  type: visitor-counter
  url: //visitor-counter.cerallin.top/count.php
  # or
  # type: busuanzi

# word cloud
word_cloud:
  python_path: python3
  output_path: images/word-cloud.svg
  word_num: 100
  # python
  mask_image: source/_jieba/Lain.png
  mask_image_color: source/_jieba/Lain-color.png
  max_font_size: 60
  # user dicts
  user_dict: source/_jieba/user_dict.utf-8
  stop_word_dict: source/_jieba/stop_word_dict.utf-8

# hexo-generator-search
search:
  path: meta.json
  field: post
  content: false

# Server
server:
  port: 4000
  log: false
  ip: 0.0.0.0
  compress: false
  cache: false
  header: true
  serveStatic:
    extensions:
      - html
#
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Cerallin/notes.git
  branch: gh-pages
